// using csv scripts
const SCRIPTED_ANIMS = [
	'One-Hand Handjob',
	'Standing One-Hand Handjob',
	'Seated One-Hand Handjob',
	'Two-Hand Handjob',
	'Standing Handjob & Ballrub',
	'Standing Onahole Handjob',
	'Tip & Shaft Licking',
	'Seated Tip & Shaft Licking',
	'One-Hand Blowjob',
	'Standing One-Hand Blowjob',
	'Two-Hand Blowjob',
	'Seated Two-Hand Blowjob',
	'Standing Two-Hand Blowjob',
	'Glans Rubbing',
	'Standing Glans Rubbing',
	'Seated Glans Rubbing',
	'Crowded Handjob',
	'Seated No-Hand Tip Licking',
	'Standing Handjob & Ball Licking',
	'Sitting Blowjob',
	'Bench Blowjob',
	'Standing No-Hand Blowjob',
	'Paizuri',
	'Standing Paizuri',
	'Seated Paizuri',
	'Pool Paizuri',
	'Seated Paizuri & Licking',
	'Hand-Assisted Paizuri',
	'Stated Hand-Assisted Paizuri',
	'Standing Hand-Assisted Paizuri',
	'Seated Hand-Assisted Paizuri',
	'Pressed Paizuri',
	'Paizuri & Sucking',
	'Seated Paizuri & Sucking',
	'Standing Paizuri & Sucking',

	'Missionary',
	'Holding Legs Missionary',
	'Piledriver Missionary',
	'Cowgirl',
	'Sofa Cowgirl',
	'Seated Facing',
	'Leg Lifted Facing Against Wall',
	'Doggystyle',
	'Arm-Grab Doggystyle',
	'Arm-Grab Doggystyle Against Seat',
	'Doggystyle Against Chair',
	'Doggystyle Against Desk',
	'Arm-Grab Doggystyle Against Desk',
	'Doggystyle Against Wall',
	'Leg Lifted Doggystyle Against Wall',
	'Doggystyle In Pool',
	'Doggystyle Against Fence',
	'Vaulting Horse Doggystyle',
	'Lying Doggystyle',
	'Spooning',
	'Seated Spooning',
	'Spooning on Desk',
	'Standing',
	'Ekiben',
	'Ekiben Grabbing Fence',
	'Laying On Desk',
	'Mating Press',
	'Pressed From Behind',

	// Onanie
	'Masturbating While Standing', 'Standing masturbation', '立ちオナニ',
	'Masturbating In Chair', 'Chair masturbation', '椅子オナニー',
	'Masturbating Against Corner', 'Corner masturbation', '角オナニー',

	// Yuri
	'Tribbing', '具合わせ',
	'Mutual Groping', '互い弄り',
	'Chair Cunnilingus', '椅子クンニ',

	// FFM
	'Wフェラ', 'Fellatio',
	'Wフェラ入れ替え', 'Fellatio Switch',
	'後背位手マン', '3P Doggystyle',
	'後背位手マン入れ替え', '3P Doggystyle Switch',
	'騎乗位クンニ', '3P Cowgirl',
	'騎乗位クンニ入れ替え', '3P Cowgirl Switch',

	// Darkness
	'Chest Massaged Handjob', '胸揉まれ手コキ',
	'Irrumatio', 'イラマチオ',
	'Fellatio & Handjob', 'フェラ＆手コキ',
	'Pinned Missionary', '押さえ正常位',
	'Pinned Spooning', '押さえ側位',
	'Doggy & Fellatio', 'バック＆フェラ',

	'亀頭いじり',
	'片手コキ',
	'両手コキ',
	'椅子亀頭いじり',
	'椅子片手コキ',
	'立ち亀頭いじり',
	'立ち片手コキ',
	'立ち手コキ玉いじり',
	'立ちオナホ手コキ',
	'密着手コキ',
	'先舐め＋竿舐め',
	'片手フェラ',
	'両手フェラ',
	'椅子先舐め＋竿舐め',
	'椅子ノーハンド先舐め',
	'椅子両手フェラ',
	'立ち玉舐め手コキ',
	'立ち片手フェラ',
	'立ち両手フェラ',
	'立ちノーハンドフェラ',
	'椅子またがりフェラ',
	'ベンチフェラ',
	'パイズリ',
	'腕はさみパイズリ',
	'押し付けパイズリ',
	'パイズリ+咥え',
	'椅子パイズリ',
	'椅子腕はさみパイズリ',
	'椅子パイズリ+舐め',
	'椅子パイズリ+咥え',
	'立ちパイズリ',
	'立ち腕はさみパイズリ',
	'立ちパイズリ+咥え',
	'プールパイズリ',

	'正常位',
	'開脚正常位',
	'後背位',
	'腕引っ張り後背位',
	'騎乗位',
	'側位',
	'立位',
	'駅弁',
	'椅子対面',
	'椅子背面',
	'椅子バック',
	'腕引っ張り椅子バック',
	'机寝位',
	'机バック',
	'腕引っ張り机バック',
	'机側位',
	'壁対面片足上げ',
	'壁バック',
	'片足上げ壁バック',
	'プールバック',
	'フェンス後背位',
	'フェンス掴まり駅弁',
	'種付けプレス',
	'マングリ正常位',
	'跳び箱バック',
	'寝バック',
	'ソファ騎乗位',
	'押し付けバック',

] as const;

export default SCRIPTED_ANIMS;