import TSupportedAnims from './types/TSupportedAnims';

const SUPPORTED_ANIMS: TSupportedAnims[] = [
	'One-Hand Handjob',
	'Standing One-Hand Handjob',
	'Seated One-Hand Handjob',
	'Two-Hand Handjob',
	'Standing Handjob & Ballrub',
	'Standing Onahole Handjob',
	'Tip & Shaft Licking',
	'Seated Tip & Shaft Licking',
	'One-Hand Blowjob',
	'Standing One-Hand Blowjob',
	'Two-Hand Blowjob',
	'Seated Two-Hand Blowjob',
	'Standing Two-Hand Blowjob',
	'Glans Rubbing',
	'Standing Glans Rubbing',
	'Seated Glans Rubbing',
	'Crowded Handjob',
	'Seated No-Hand Tip Licking',
	'Standing Handjob & Ball Licking',
	'Sitting Blowjob',
	'Bench Blowjob',
	'Standing No-Hand Blowjob',
	'Paizuri',
	'Standing Paizuri',
	'Seated Paizuri',
	'Pool Paizuri',
	'Seated Paizuri & Licking',
	'Hand-Assisted Paizuri',
	'Stated Hand-Assisted Paizuri',
	'Standing Hand-Assisted Paizuri',
	'Seated Hand-Assisted Paizuri',
	'Pressed Paizuri',
	'Paizuri & Sucking',
	'Seated Paizuri & Sucking',
	'Standing Paizuri & Sucking',
];

export default SUPPORTED_ANIMS;